const CalcContentCpMapping = {
    tableName: "작품",
    id: "아이디",
    content_type: "작품 유형",
    content_group1: "작품 그룹1",
    content_group2: "작품 그룹2",
    content_title: "작품 제목",
    series_title: "시리즈 제목",
    author: "저자",
    author_draw: "그림 저자",
    author_translate: "번역 저자",
    author_etc: "기타 저자",
    publisher: "출판사",
    cp_name: "저작권자",
    cp_info: "저작권자 정보",
    date_publish: "출판날짜",
    category_main: "메인 카테고리",
    category_sub: "서브 카테고리",
    flag_complete: "완결여부",
    flag_adult: "성인여부",
    keywords: "키워드",
    price: "가격",
    price_sales: "할인가격",
    flag_sole_contract: "단독계약여부",
    date_start_sole: "단독계약 시작날짜",
    date_end_sole: "단독계약 종료날짜",
    total_episode: "총 회수",
    total_free_episode: "총 무료회수",
    sales_type: "서비스 유형",
    service_country: "서비스중인 국가",
    country_code: "국가코드",
    original_ip: "원작",
    flag_service: "서비스 여부",
    service_add_info: "추가정보",
  };
  
  export default CalcContentCpMapping;
  