const CAL_RAW_SHEET_HEADER = [
    "매출 코드"
    , "정산월"
    , "판매월"
    , "서비스"
    , "거래처 코드"
    , "서비스 상세"
    , "플랫폼 코드"
    , "플랫폼 상세코드"
    , "서비스 지역"
    , "플랫폼측 컨텐츠 코드"
    , "제목"
    , "저자"
    , "출판사"
    , "저작권자"
    , "무료이용 건수"
    , "구매 건수"
    , "구매 금액"
    , "대여 건수"
    , "대여 금액"
    , "자유이용권 건수"
    , "자유이용권 금액"
    , "취소 건수"
    , "취소 금액"
    , "결제수수료 보정액"
    , "총매출(구매금액+대여금액-취소금액)"
    , "앱마켓 수수료율"
    , "총매출 - 앱마켓 수수료"
    , "제휴사 수수료율"
    , "수수료율 합계"
    , "순매출(총매출 - 제휴사 수수료)"
    , "외화수수료 보정 순매출"
    , "종합 CP 정산율"
    , "종합 CP 정산금"
    , "수익"
    , "작품 유형"
    , "컨텐츠번호"
    , "시리즈명"
    , "시리즈번호"
    , "매출유형"
    , "선수수익 관리코드"
    , "외화정산금액"
    , "통화"
    , "환율"
    , "외환 입금비율"
    , "비고"
    , "세금보정"
    , "세금포함여부"
    , "CP1"
    , "CP1 코드"
    , "CP1 정산코드/선급원가 코드"
    , "CP1정산기준"
    , "CP1 정산율"
    , "CP1 선차감 제외 정산률"
    , "CP1 정산금"
    , "CP1 정산 구분"
    , "CP1 비고"
    , "CP2"
    , "CP2 코드"
    , "CP2 정산코드/선급원가 코드"
    , "CP2정산기준"
    , "CP2 정산율"
    , "CP2 선차감 제외 정산률"
    , "CP2 정산금"
    , "CP2 정산 구분"
    , "CP2 비고"
    , "CP3"
    , "CP3 코드"
    , "CP3 정산코드/선급원가 코드"
    , "CP3정산기준"
    , "CP3 정산율"
    , "CP3 선차감 제외 정산률"
    , "CP3 정산금"
    , "CP3 정산 구분"
    , "CP3 비고"
    , "CP4"
    , "CP4 코드"
    , "CP4 정산코드/선급원가 코드"
    , "CP4 정산기준"
    , "CP4 정산율"
    , "CP4 선차감 제외 정산률"
    , "CP4 정산금"
    , "CP4 정산 구분"
    , "CP4 비고"
    , "매출반영월"
    , "정산여부"
    , "증빙번호"
]

export default CAL_RAW_SHEET_HEADER

// address: "낙성대역3길 111"
// bank: "기업은행"
// bank_account_holder: "박유경"
// bank_account_name: "박유경"
// bank_account_number: "41206658101015"
// bank_account_text: null
// bank_code: null
// contract: null
// cp_account_number: "1234567890"
// cp_code: "12345    "
// cp_name: "박유경2"
// cp_name_org: null
// cp_pen_name: "박유경"
// cp_type: "개인"
// cp_type_code: "P"
// description: "박유경"
// email: null
// email_org: null
// id: 432
// manager1: "박유경"
// manager2: "박유경"

// add_info: "리빙툰"
// b2b_rate: 0
// b2b_rate_std: ""
// b2bc_rate: 50
// b2bc_rate_std: "순매출"
// b2c_down_rate: 50
// b2c_down_rate_std: "순매출"
// b2c_fixed_rate: 50
// b2c_fixed_rate_std: "순매출"
// b2c_rent_rate: 50
// b2c_rent_rate_std: "순매출"
// cp_id: 652
// cp_name: "이정준 외"
// cp_service_country: "국내"
// cp_type: "개인"
// date_send: "익익월 말일"
// id: 321